version: "3.9"

services:
  database:
    container_name: database
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: bookdelivery
      MYSQL_PASSWORD: ippavlova_1990
      MYSQL_ROOT_PASSWORD: ippavlova_1990
      MYSQL_ROOT_HOST: '%'
      MYSQL_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - bookDeliveryNetwork

  bookdelivery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookdelivery
    restart: on-failure
    ports:
      - "1221:1221"
    environment:
      - server.port=1221
      - spring.datasource.username=root
      - spring.datasource.password=ippavlova_1990
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3307/bookdelivery
    depends_on:
      - database
    networks:
      - bookDeliveryNetwork


networks:
  bookDeliveryNetwork: