name: Publish git tag as ECR image

on:
  create:
    tags:
      - '*'

env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  DOCKERFILE: ./src/infrastructure/Dockerfile
  GIT_TAG: ${{ github.ref_name }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in into Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # This step is tailored specifically for docker hub,
      # see the action docs for other registries
      - name: Build and publish image on Docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:${{ env.GIT_TAG }} , ${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:latest
          push: true